version: '3'
services: 
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: rapla_db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: rapla_db_user
      # You can use whatever password you like
      MYSQL_PASSWORD: abracadabrabric
      # Password for root access
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      #MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  web: 
    image: rapla_tomcat:latest
    environment:
      USER_MYSQL: rapla_db_user
      # So you don't have to use root, but you can if you like
      PASS_MYSQL: abracadabrabric
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on: 
      - db
# Names our volume
volumes:
  my-db:
  


